### ISSUE TITLE
Run doWeb only returns Translation successful

### ISSUE THREAD

**Issue by akinhwan** [zotero/scaffold#101]
Hello, 

Is there a way to get better debug information when I run doWeb() in Scaffold?
Currently, I just get this one line logged, and it is not very helpful. 

> 11:53:01 Translation successful

How would you recommend also I log things (sort of like console.log() in the browser. I'm trying to view what my getUID function is returning.

**Comment by adam3smith** [comment]
when you successfully run `doWeb`, you'll get the imported Zotero item as JSON. If you just get Translation successful, that's an empty (and thus presumably actually unsuccessful) import.

You can use `Zotero.debug()` in lieu of `console.log()` to get debug output throughout the translation process.
