### ISSUE TITLE
Testing..."New Web": status is "Creation Failed"

### ISSUE THREAD

**Issue by akinhwan** [zotero/scaffold#102]
From the **Testing** tab in Scaffold, when I press "New Web" in order to create a new test from the current browser page, the "input" is https://www.ncbi.nlm.nih.gov/labs/pubmed/21249754-cancer-syndromes-internet/?from_single_result=NBK1825 and status is "Creation failed" 
The same url without /labs/ creates New Tests successfully that I'm able to Save.
Any idea what steps I can take to generate a testCase json?

Also running tests that I populate from loaded translator PubMed.js sometimes return the status "Detection returned wrong item type" that 
refers to the value assigned in `items[ { itemType } ]` in the testCase right?

**Comment by adam3smith** [comment]
For 1: That should work if the `doWeb` button in Scaffold successfully produces an imported item (i.e. shows the Zotero JSON for the item in the right-hand panel, followed by Translation successful. Are you sure it does that?

2. "Detection returned wrong item type" means that the value returned by `detectWeb` doesn't correspond to items.itemType populated by `doWeb` on the same page. E.g. if detect returns `journalArticle` but then the item is imported as `bookSection`.
