### ISSUE TITLE
Scaffold is now a bundled developer tool

### ISSUE THREAD

**Issue by dstillman** [zotero/scaffold#112]
In the latest Zotero beta, Scaffold is a built-in tool that's available via the new Developer menu as "Translator Editor".

I'm planning to push a final version of the Scaffold extension that removes all files and updates the extension title to say to uninstall it. (We could probably auto-uninstall it, but the majority of people who have Scaffold installed probably will also read this issue. Fortunately, that's about to change!)

**Comment by zuphilip** [comment]
This looks interesting! Then everybody can use Scaffold aka Translator Editor without installing an additional plugin.

At the moment it is also easy to develop Scaffold and test it with a linked plugin version: https://github.com/zotero/scaffold#development . Will this just continue to work? Or is there another easy way to develop and test Scaffold in the future?

**Comment by dstillman** [comment]
That won't be possible, because zotero/scaffold will be cleared of files and deleted, and the parts of it that are now in zotero/zotero will no longer run as an extension. (I suppose technically you could keep the shell of an extension and rsync files back and forth, but that seems more complicated than just using a Zotero source build.)

While it'd technically be possible to ship it as a bundled extension, that's buggy and annoying and would need to change again with Electron anyway, and there's just really not much reason to deal with that. The few people who work on Scaffold will need to set up [Zotero source builds](https://www.zotero.org/support/dev/client_coding/building_the_standalone_client) if they don't have them, the same as when working on the built-in style editor or other things. If you don't yet have a source build, I can help if you run into trouble setting it up.

(Having this in zotero/zotero also means we can now use ACE for other things in zotero/zotero such as the style editor or Run JavaScript window.)

**Comment by dstillman** [comment]
Zotero 5.0.73 is now out with Scaffold included.

**Comment by zuphilip** [comment]
Okay, I will look into how to build Zotero from source (some time later). Thank you for the clarification and the offer for helping with troubles there.
