### ISSUE TITLE
Scaffold fails to create a test from web page

### ISSUE THREAD

**Issue by aurimasv** [zotero/scaffold#15]
or something of the sort. Making a note here until I have a chance to investigate.

http://www.amazon.com/Mark-LeBar/e/B00BU8L2DK

(if someone can confirm this that would be great)

**Comment by owcz** [comment]
I think this is resolved. I just opened the Amazon translator in Scaffold, added the above page, clicked "Run" and the result was "Test succeeded", as expected.
