### ISSUE TITLE
Show URL of active Firefox tab in Scaffold

### ISSUE THREAD

**Issue by rmzelle** [zotero/scaffold#18]
During his Zotero translator webinar, @adam3smith mentioned a common problem: trying to run a translator in Scaffold while you have the wrong Firefox tab selected.

Maybe we should show the URL of the active Firefox tab in Scaffold, so you can quickly verify that you have the right tab?

**Comment by aurimasv** [comment]
Closed by 7ec9460bdcbf8bb97b47c26da732feb7e43e22db
