### ISSUE TITLE
Testing in Scaffold not working

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#26]
It seems for me that running any tests in scaffold is not working. @adam3smith @aurimasv Can you still run tests in scaffold or can you reproduce the error?

My browser console shows the error:
```
TypeError: items[i].getElementsByTagName is not a function scaffold.js:928:4
```

**Comment by adam3smith** [comment]
same problem. I can create but not run.

**Comment by zuphilip** [comment]
Okay, I debbuged the problem further. It looks that first the loop variable `i` equals `0` which is okay and then the variable equals `append` (function name) and the error happens: 

![scaffold-error](https://cloud.githubusercontent.com/assets/5199995/14233704/4c1bc4c2-f9d0-11e5-85d1-023955de849a.jpg)

I guess we have to rewrite the for-loop here... Would you agree that it should be simply be
```
for (var i=0; i<items.length; i++) {
```
?

**Comment by aurimasv** [comment]
Yes, but where is the "append"coming from? Sounds like something is
modifying the array prototype, which is ok, I guess, but that shouldn't be
our code.

**Comment by zuphilip** [comment]
I just tested that loop separately: `for (j in items) { Zotero.debug(j); }` gives
```
(3)(+0006464): 0
(3)(+0000000): append
(3)(+0000000): remove
(3)(+0000000): item
(3)(+0000000): length
```
Thus, it seems that these are the functions/methods of (the object) `items`. No?

**Comment by zuphilip** [comment]
@aurimasv `items` is a ChromeNodeList and not an array. Does this make sense?

**Comment by zuphilip** [comment]
Hm.. the for loops seem to work now in https://github.com/zuphilip/scaffold/commit/e8052b194bb0d25567ee901e9ba5b12ca1a1bcd0, but there is another error when trying to update a test:
```
TypeError: listbox.selectedItems.slice is not a function
```
My impression is that `selectedItems` changed its type to ChromeNodeList.

**Comment by zuphilip** [comment]
Okay, I think I fixed it.

**Comment by dstillman** [comment]
Changed in https://bugzilla.mozilla.org/show_bug.cgi?id=120684, BTW

(Along with `[...listbox.selectedItems]`, `Array.from(listbox.selectedItems)` also works for this sort of thing.)
