### ISSUE TITLE
Regexp fail under FF46

### ISSUE THREAD

**Issue by fbennett** [zotero/scaffold#30]
In Firefox 46, I'm getting this error when opening a translator in Scaffold, with empty content under all tabs:
```
TypeError: m is null
```
The error comes from lines 196-198 of `scaffold.js`:
``` javascript
var m = /^\s*{[\S\s]*?}\s*?[\r\n]+/.exec(header);
// Detect the minified framework and strip it
var usesFW = (translator.code.substr(m[0].length).indexOf("/* FW LINE ") !== -1);
```
Not sure why that would fail. Has the meaning of `\S` changed? Or maybe I'm missing something else.

**Comment by zuphilip** [comment]
Can you copy the code of your translator with empty content here?

**Comment by fbennett** [comment]
Sorry, false alarm. I had tested in Juris-M before merging the latest changes to Zotero. It works fine with an updated client.
