### ISSUE TITLE
Update Translator Framwork

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#32]
The translator framework was updated in https://github.com/egh/zotero-transfw/pull/1 to reflect the change to `versionNumber` in API v3 for `computerPrograms`. Now, we also need to update the module here: https://github.com/zotero/scaffold/blob/master/src/resource/modules.json . @dstillman, you did work with that file before, right? Especially you did the minimified version. Maybe you can help with this?

**Comment by avram** [comment]
I think you just run `modules.py`
