### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by josve05a** [zotero/scaffold#33]
I've never used Scaffold before, but I think that when I open it in Firefox, the ID field should be generated, and the current tab URL should populate, and that the buttons on the page should do anyhing. In Windows 10, Firefox 45, and latest version of Scaffold. Nothing happens in the tool at all. I tried older versions of the tool, I tried older versions of Firefox (I am usiúally on Nightly, but tried the old FF 45 now as well). I'm guessing it is an OS issue?

![image](https://cloud.githubusercontent.com/assets/7117013/17534984/5760b20e-5e8c-11e6-9ad2-640b1329310a.png)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by zuphilip** [comment]
If you want to edit an existing translator, then you have to load it (best and easiest from an example website for this translator). If you want to write a new translator you have to fill in all the details here yourself and generate a new translator ID.

**Comment by josve05a** [comment]
@zuphilip I've tried to wrie a new translator, but nothing happens when I press e.g. Test Regex, or Generate, or the small icon-buttons like  load at the top. Nothing.

**Comment by josve05a** [comment]
@zuphilip See this screencast
https://www.youtube.com/watch?v=d93e94W036w

**Comment by zuphilip** [comment]
Ah, sorry you need Zotero installed for Scaffold.

**Comment by josve05a** [comment]
@zuphilip I've just started wring on my first translator, and it seems to work ok, but I need some help fixing trailing an starting newlines which are generated when runnning the code. Mind having a look at it for me, so I can learn? http://dpaste.com/2VM9WR5
