### ISSUE TITLE
Make Scaffold ready for Zotero 5.0

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#34]
Currently Scaffold is not working with the beta releases of Zotero 5.0. It is critical to have a good tool for working with translators and Scaffold suits this purpose quite nice. I guess that it even may be not _that_ complicated, since the code base is not that large, but I have not much experience with calling Zotero translators. @dstillman Is this an easy update for you?

**Comment by dstillman** [comment]
Standalone compatibility: https://github.com/zotero/scaffold/issues/36
Further discussion: https://groups.google.com/d/topic/zotero-dev/Mqu2IUWgFBE/discussion
