### ISSUE TITLE
Matching Translators is always empty now

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#41]
After the newest commit with Zotero 5.0: When opening an url in the Scaffold browser, and then try to find the matching translator(s), I don't see any results, e.g.

![scaffold-matching](https://user-images.githubusercontent.com/5199995/30785501-d47cd046-a167-11e7-87ba-2c1520415bd0.png)

CC @adomasven

**Comment by adam3smith** [comment]
yes, same here.
