### ISSUE TITLE
Remove framework checkbox and automatically add attr()/text()

### ISSUE THREAD

**Issue by dstillman** [zotero/scaffold#43]
Part of https://github.com/zotero/translators/issues/1277

We could have a checkbox for attr()/text(), but since they'll be available in the sandbox in future 5.0 versions, we could probably just scan for those functions and insert them if they're used.

**Comment by zuphilip** [comment]
Would it still be possible to maintain the FW translators afterwards? At least for a short time because it might take time to rewrite all these translators...

**Comment by dstillman** [comment]
Yeah, if we take out the checkbox, Scaffold just wouldn't know anything about that code block and would leave it in place.
