### ISSUE TITLE
"Add Item Template" button

### ISSUE THREAD

**Issue by dstillman** [zotero/scaffold#44]
Seems like we should have a button that lets you select an item type and get an object literal with the fields for that item type. This would more closely mimic what the framework (which is being [removed from Scaffold](https://github.com/zotero/scaffold/issues/43)) provides and, even for translators with more complicated logic, make it easy to see the available fields.

**Comment by zuphilip** [comment]
Okay, I working on this. @dstillman Can you give me a hint how to generate an item template? I only have seen this function in the Web API...

**Comment by dstillman** [comment]
Probably `Zotero.ItemFields.getItemTypeFields(itemTypeID)` + `Zotero.ItemFields.getName(fieldID)` plus some hard-coded additions (for `attachments`, etc.)

**Comment by dstillman** [comment]
Added in https://github.com/zotero/scaffold/pull/46
