### ISSUE TITLE
Search and Replace in ACE

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#49]
[ACE ](https://ace.c9.io/) seems to have a nice search and replace feature. How can this be used in Scaffold?

![ace-search](https://user-images.githubusercontent.com/5199995/31309507-6b911996-ab87-11e7-9fae-4fccdf112ebb.png)

**Comment by dstillman** [comment]
(I don't think we'll put in any time improving the integrated editor, though you're welcome to work on it. Scaffold supports editing via an external editor with automatic reloading, and personally that's the only way I'd ever use it — I'd even be happy taking ACE out altogether and just making it easier to open a given translator in an external editor. But maybe the editor is useful for people without a preferred text editor.)

**Comment by zuphilip** [comment]
Okay, I understand that this is not very important for you or even negligible. Personally, I use the editor of Scaffold for most coding and it works fine for me. Moreover, with the new templating things the internal editor might become more handy than any external editor.

Search and replace looks like a standard feature of ACE and therefore I just wondering, why it is not "enabled" in Scaffold. But maybe it is an extension of ACE. I will look into this...

**Comment by zuphilip** [comment]
Solved in #50 https://github.com/zotero/scaffold/pull/50/commits/4c1ea4fe877a905edba90b7ae82e38c42d404e95
