### ISSUE TITLE
Updating tests does not work anymore

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#51]
I can't update tests in Scaffold after updating to Zotero 5.0.23 (nothing else changed as far as I know). It starts and the status switches to "Updating" and I see the message "Page loaded" but then nothing more happens. In the Zotero log I see these two messages:
```
[JavaScript Error: "TypeError: hiddenBrowser.docShell is undefined" {file: "chrome://scaffold/content/scaffold.js" line: 1035}]
Scaffold</TestUpdater.prototype._updateTests@chrome://scaffold/content/scaffold.js:1035:3
Scaffold</TestUpdater.prototype.updateTests@chrome://scaffold/content/scaffold.js:962:3
updateSelectedTests@chrome://scaffold/content/scaffold.js:929:3
oncommand@chrome://scaffold/content/scaffold.xul:1:1


[JavaScript Error: "TypeError: doc is undefined" {file: "chrome://scaffold/content/scaffold.js" line: 1007}]
```

CC @dstillman @adomasven

**Comment by zuphilip** [comment]
Another thing which I see now: When I open an url in the browser in Scaffold, then Zotero and Scaffold become very slow, such that I cannot work with them in a reasonable way, and my CPU activity is going up. After closing Saffold again, everything went to normal again. The Zotero log shows this entry:
```
[JavaScript Error: "[Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIInterfaceRequestor.getInterface]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: resource://gre/components/nsSidebar.js :: nsSidebar.prototype.init :: line 20"  data: no]"]
nsSidebar.prototype.init@resource://gre/components/nsSidebar.js:20:17
browserCheck@http://www.mitpressjournals.org/wro/product.js:1390:160
@http://www.mitpressjournals.org/wro/product.js:1391:9
```

**Comment by dstillman** [comment]
Fixed, though it looks like saving wouldn't have actually worked in a Scaffold source install all year.

I can't reproduce the CPU issue. If you're still seeing that with the latest version, can you open a new issue with the steps to reproduce?
