### ISSUE TITLE
Show browser pane only on the left part

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#53]
The browser tab is great to open a specific website and then adjust the translator for this example. I switched back and forth from browser tab to Scaffold tab, where I then only can see the test results. My impression is that it makes more sense to have the browser pane only in the left part, such that I can then compare it to the test result directly and switch easily to the code tab (only one click instead of two). Something like this:

![scaffold-draft](https://user-images.githubusercontent.com/5199995/32280713-0f3138da-bf1d-11e7-8627-c6bd707b8a48.jpg)

What do you think?  CC @adam3smith

**Comment by adam3smith** [comment]
Yes, totally agree. I found the set-up a bit uncomfortable to use but couldn't quite put a finger on what the problem is. I think that's really it -- being able to see page & results at same time makes this much smoother.

**Comment by zuphilip** [comment]
Done with #55.
