### ISSUE TITLE
Firefox quantum ? 

### ISSUE THREAD

**Issue by symac** [zotero/scaffold#58]
That might have been explained somewhere but I have not been able to find the information. I just tried to install Scaffold on my current version of Firefox (57) and FF tells me it is not possible as Scaffold is not compatible. Is something planned to fix that ? Or a way to force install on FF 57 that should be added to the README?

**Comment by adam3smith** [comment]
you don't install in Firefox, you install in Zotero. (Scaffold has a browser pane of its own now where you can load pages for testing)

**Comment by symac** [comment]
Sorry @adam3smith for not having searched more and thanks for the quick answer!

**Comment by adam3smith** [comment]
this is hard to find. We'll be updating Scaffold documentation as soon as possible.
