### ISSUE TITLE
Error with DOMParser for html in tests

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#74]
There seems to be an error in Scaffold tests when using DOMParser for html, e.g.
```js
		var parser = new DOMParser();
		var html = parser.parseFromString(text, "text/html");
```

As it is also used in [DAI-Zenon translator](https://github.com/zotero/translators/blob/3376a48f5cb9e6479a63d09847705b2d42c88fbb/DAI-Zenon.js#L91-L92). The first test case there for https://zenon.dainst.org/Record/000269027 results now in the following error
```
12:11:38 Translation using DAI-Zenon failed: 
         string => Error: error parsing XML
         stack => Zotero.Translate.SandboxManager/this.sandbox.DOMParser/wrappedObj.parseFromString@chrome://zotero/content/xpcom/translation/translate_firefox.js:387:33
         scrape/<@DAI-Zenon:80:13
         Zotero.Utilities.Translate.prototype.doGet/xmlhttp<@chrome://zotero/content/xpcom/utilities_translate.js:330:5
         _stateChange@chrome://zotero/content/xpcom/http.js:1047:6
         Zotero.HTTP</this.doGet/xmlhttp.onreadystatechange@chrome://zotero/content/xpcom/http.js:400:4
         
         url => https://zenon.dainst.org/Record/000269027
         downloadAssociatedFiles => true
         automaticSnapshots => true
```

However, the same url works fine when loaded in the browser tab. @dstillman Any idea how to fix this?

**Comment by zuphilip** [comment]
@dstillman This error is getting quite annoying because I cannot easily do testing e.g. in ScienceDirect translator which also relies on DOMParser. Maybe also something in Zotero itself changed?

**Comment by dstillman** [comment]
Moved to https://github.com/zotero/zotero/issues/1502
