### ISSUE TITLE
Keyboard shortcuts and easier URL selection

### ISSUE THREAD

**Issue by adam3smith** [zotero/scaffold#77]
Coming out of #76 two suggestions to reduce clicking around:

1. Assign keyboard shortcuts to `doWeb` `doDetect` and (not mentioned in that thread but IMO also useful) save

2. Allow for easier opening of test URLs in browser (to prevent the cumbersome "select URL in test, copy to browser" steps.) I could see an elegant being just a dropdown on the right of the URL bar in the browser tab making all test URLs accessible, but there are obviously other ways of doing the same.

**Comment by zuphilip** [comment]
_To 1:_ We can add the parameter `accesskey` to the toolbar buttons, e.g. in https://github.com/zotero/scaffold/blob/594ea06fcc1a10a39aa039fb7b958b2271feeddb/src/chrome/content/scaffold/scaffold.xul#L73

add `accesskey="R"` which then can be invoked by pressing Alt+R on my Windows machine. Would that be the way to go?

We could use:
* Alt+R for "Run doWeb"
* Alt+D for "Run detectWeb"
* Alt+S for "Save"

However, this then only focus on the web translators and let the e.g. import translators not supported by keyboard shortcuts. Is that okay?

After playing around a little with such keyboard shortcuts my impression is that I will click the buttons again, because that as fast as pressing two keys and easier to memorize.

_To 2:_ That is an interesting idea with the dropdown. We will have to look what is (easily) possible to implement.

**Comment by dstillman** [comment]
No, we don't want Alt. We can use [`<key>`](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Keyboard_Shortcuts) with `accel`, which will use Ctrl or Cmd as appropriate for the platform. The key can invoke a given `<command>`, which can also be called by a `<menuitem>` that communicates the key. (We'll need something else post-XUL, but a JS-based option would have to change anyway, so might as well just use what's easy.) See [standalone.xul](https://github.com/zotero/zotero/blob/71bee9cfe74b491f9422129d0e13eb38f92f8f44/chrome/content/zotero/standalone/standalone.xul) for an example of keys, commands, and menu items together.

**Comment by dstillman** [comment]
> However, this then only focus on the web translators and let the e.g. import translators not supported by keyboard shortcuts. Is that okay?

I forget — do we have translators that are both import and web? If not, it could just be context dependent. Or even if we do have some with both, it could still prioritize *Web if they exist and otherwise run *Import.

**Comment by dstillman** [comment]
> How about CTRL+T for deTection?

Fine with me.

**Comment by zuphilip** [comment]
I have a almost finished solution for the second point with an editable [menulist](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/menulist):

![scaffold-url-dropdown](https://user-images.githubusercontent.com/5199995/37255471-15aab5a6-254d-11e8-8a11-2149b32c0c8a.png)

However, during browsing we need to update the browser url, which does not work anymore:

https://github.com/zotero/scaffold/blob/594ea06fcc1a10a39aa039fb7b958b2271feeddb/src/chrome/content/scaffold/scaffold.js#L1137

My guess is that `value` is different here, but also `label` does not work. Any ideas how to fix this?

**Comment by dstillman** [comment]
Can I see it on a branch?

**Comment by zuphilip** [comment]
Sure, see #79.

**Comment by dstillman** [comment]
Oh, it's just that it's using `textbox.browser-url` for the selector, but it's no longer a `textbox` — it's now a `menulist`. Changing it to just `.browser-url` would work.

**Comment by zuphilip** [comment]
Yes! Thank you! Now the PR is updated and ready.

(I tried similar things before, but with `setAttribute`...)

**Comment by zuphilip** [comment]
@adam3smith Both points here are now implemented and I build a new beta release for you:

[scaffold-beta-2018-03-13.xpi.TXT](https://github.com/zotero/scaffold/files/1805841/scaffold-beta-2018-03-13.xpi.TXT) (You have to delete the TXT file ending again.)

Can we close this issue?

I opened another issue #80 for copying to clipboard resp. (real) browser.

**Comment by zuphilip** [comment]
Everything from this issue should be implemented in v3.3.2.
