### ISSUE TITLE
Update fails with hash error

### ISSUE THREAD

**Issue by adam3smith** [zotero/scaffold#95]
I haven't looked into this, but trying to update to 3.3.2. using check update produces
addons.xpi	WARN	Download of https://github.com/zotero/scaffold/releases/download/v3.3.2/scaffold-3.3.2.xpi failed: Downloaded file hash (a5a859b487ef6fac21482a0a5ed17527a11c36d7) did not match provided hash (a5a859b487ef6fac21482a0a5ed17527a11c36d7bbbd2f448dac18728ee4c7d596ead69af107679fda513b587891599c2522cec5b0acd1175b165c57)

**Comment by zuphilip** [comment]
Oh, that is a bug. It seems that the new sha-code is just appended at the beginning. I will look into it...

**Comment by zuphilip** [comment]
The same already happened when releasing v3.3.1 https://github.com/zotero/scaffold/commit/594ea06fcc1a10a39aa039fb7b958b2271feeddb#diff-346c9b3bf31e4501ac414fd9b36e29caL17 but the automatic updating was then not yet ready.

**Comment by zuphilip** [comment]
@adam3smith Can you try again now?

**Comment by adam3smith** [comment]
yes, that worked, thanks!
