### ISSUE TITLE
Error: Zotero_TranslatorTester is undefined

### ISSUE THREAD

**Issue by zuphilip** [zotero/scaffold#99]
The testing in Scaffold does not work anymore and I see the error:
```js
[JavaScript Error: "Zotero_TranslatorTester is undefined" {file: "chrome://scaffold/content/scaffold.js" line: 568}]
```
Could this be related to some changes in Zotero? I am running the latst Zotero Beta, i.e. 5.0.57-beta.10+30291328e. CC @adomasven

**Comment by dstillman** [comment]
Fixed in zotero/zotero@b80c405da44e716a3cde541903c030a90de5c060.
